version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcription_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcription_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge